service: R2D2
 
provider:
  name: aws
  runtime: python3.10
  stage: prod
  region: eu-north-1
 
functions:
  extractTextFromFile:
    handler: extractTextFromFile.main
  countToken:
    handler: countToken.main

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    dockerizePip: true
