service: R2D2
 
provider:
  name: aws
  runtime: python3.10
 
functions:
  extractTextFromFile:
    handler: extractTextFromFile.main

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    dockerizePip: true
